2022-02-28 18:26:42,699 INFO: Microblog startup [in C:\Users\Destiny\Downloads\Cloud Web Application Development IntroductionFile sem 2\microblog Flask Lab05\microblog\app\__init__.py:43]
2022-02-28 18:30:26,390 ERROR: Exception on /edit_profile [POST] [in C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Destiny\Downloads\Cloud Web Application Development IntroductionFile sem 2\microblog Flask Lab05\microblog\app\routes.py", line 91, in edit_profile
    db.session.commit()
  File "<string>", line 2, in commit
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 1431, in commit
    self._transaction.commit(_to_root=self.future)
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 829, in commit
    self._prepare_impl()
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 808, in _prepare_impl
    self.session.flush()
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 3363, in flush
    self._flush(objects)
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 3463, in _flush
    flush_context.execute()
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 456, in execute
    rec.execute(self)
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\persistence.py", line 236, in save_obj
    _emit_update_statements(
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\persistence.py", line 1000, in _emit_update_statements
    c = connection._execute_20(
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\sql\elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Destiny\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('man', '', 4)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-02-28 18:50:18,849 INFO: Microblog startup [in C:\Users\Destiny\Downloads\Cloud Web Application Development IntroductionFile sem 2\microblog Flask Lab05\microblog\app\__init__.py:43]
2022-02-28 18:56:16,728 INFO: Microblog startup [in C:\Users\Destiny\Downloads\Cloud Web Application Development IntroductionFile sem 2\microblog Flask Lab05\microblog\app\__init__.py:43]
2022-02-28 18:59:27,022 INFO: Microblog startup [in C:\Users\Destiny\Downloads\Cloud Web Application Development IntroductionFile sem 2\microblog Flask Lab05\microblog\app\__init__.py:43]
2022-03-08 09:39:08,141 INFO: Microblog startup [in C:\Users\Destiny\Downloads\Cloud Web Application Development IntroductionFile sem 2\microblog Flask Lab05\microblog\app\__init__.py:43]
2022-03-08 09:42:45,597 INFO: Microblog startup [in C:\Users\Destiny\Downloads\Cloud Web Application Development IntroductionFile sem 2\microblog Flask Lab05\microblog\app\__init__.py:43]
2022-03-08 09:43:01,208 INFO: Microblog startup [in C:\Users\Destiny\Downloads\Cloud Web Application Development IntroductionFile sem 2\microblog Flask Lab05\microblog\app\__init__.py:43]
2022-03-08 09:43:35,525 INFO: Microblog startup [in C:\Users\Destiny\Downloads\Cloud Web Application Development IntroductionFile sem 2\microblog Flask Lab05\microblog\app\__init__.py:43]
2022-03-08 09:44:12,205 INFO: Microblog startup [in C:\Users\Destiny\Downloads\Cloud Web Application Development IntroductionFile sem 2\microblog Flask Lab05\microblog\app\__init__.py:43]
2022-03-08 09:46:46,089 INFO: Microblog startup [in C:\Users\Destiny\Downloads\Cloud Web Application Development IntroductionFile sem 2\microblog Flask Lab05\microblog\app\__init__.py:43]
2022-03-08 09:52:17,286 INFO: Microblog startup [in C:\Users\Destiny\Downloads\Cloud Web Application Development IntroductionFile sem 2\microblog Flask Lab05\microblog\app\__init__.py:43]
